# Generated by Django 2.1.4 on 2018-12-19 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='手机号格式不对！', regex='^1[35687]\\d{9}$')]),
        ),
    ]
