# Generated by Django 2.1.4 on 2018-12-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_auto_20181219_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sh',
            field=models.IntegerField(choices=[(0, '未审核'), (1, '审核中'), (2, '审核通过')], default=1),
        ),
    ]
