# Generated by Django 2.1.4 on 2018-12-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0003_user_sh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sh',
        ),
    ]
