# Generated by Django 2.1.4 on 2018-12-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_remove_user_sh'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flower',
            field=models.TextField(default='', max_length=65535),
        ),
        migrations.AddField(
            model_name='user',
            name='star',
            field=models.TextField(default='', max_length=65535),
        ),
    ]
