# Generated by Django 2.1.4 on 2018-12-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0005_auto_20181226_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=12),
        ),
    ]
