# Generated by Django 2.1.4 on 2019-02-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0007_auto_20181228_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
