# Generated by Django 2.1.4 on 2018-12-27 10:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verify', '0005_auto_20181226_1047'),
        ('blogs', '0007_auto_20181221_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('con', ckeditor.fields.RichTextField()),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('status', models.BooleanField(default=False, verbose_name='发布状态')),
                ('look', models.IntegerField(default=0)),
                ('a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='verify.User', verbose_name='作者')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Category', verbose_name='分类')),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Keyword', verbose_name='关键字')),
            ],
        ),
    ]
