# Generated by Django 2.1.4 on 2019-01-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0007_auto_20181228_1403'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con', models.TextField(max_length=2048, verbose_name='评论内容')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='评论的日期')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Article', verbose_name='对应的博客文章')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.User', verbose_name='评论者')),
            ],
        ),
    ]
