# Generated by Django 2.1.4 on 2018-12-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_auto_20181219_2050'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('hobby', models.CharField(max_length=120)),
                ('why', models.CharField(max_length=255)),
                ('realName', models.CharField(max_length=20)),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verify.User')),
            ],
        ),
    ]
