# Generated by Django 2.1.4 on 2018-12-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '开通用户信息', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(max_length=30, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hobby',
            field=models.CharField(max_length=120, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='position',
            field=models.CharField(max_length=30, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='realName',
            field=models.CharField(max_length=20, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='why',
            field=models.CharField(max_length=255, verbose_name='申请理由'),
        ),
    ]
