# Generated by Django 2.1.4 on 2018-12-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20181220_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='why',
            field=models.TextField(max_length=1024, verbose_name='申请理由'),
        ),
    ]
