# Generated by Django 2.1.4 on 2018-12-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20181220_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='sh',
            field=models.IntegerField(choices=[(0, '未审核'), (1, '审核中'), (2, '审核通过')], default=1),
        ),
    ]
