# Generated by Django 2.1.4 on 2018-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_userinfo_sh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='why',
            field=models.CharField(max_length=1024, verbose_name='申请理由'),
        ),
    ]
