# Generated by Django 2.1.4 on 2018-12-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20181228_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(default='', max_length=30, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hobby',
            field=models.CharField(default='', max_length=120, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='position',
            field=models.CharField(default='', max_length=30, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='realName',
            field=models.CharField(default='', max_length=20, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='why',
            field=models.CharField(default='', max_length=1024, verbose_name='申请理由'),
        ),
    ]
