# Generated by Django 2.1.4 on 2018-12-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20181228_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='u',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verify.User', verbose_name='博客平台用户'),
        ),
    ]
